const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  auth: {
    login: (data) => ipcRenderer.invoke('auth:login', data),
    logout: () => ipcRenderer.invoke('auth:logout'),
    register: (data) => ipcRenderer.invoke('auth:register', data),
    getUsers: () => ipcRenderer.invoke('auth:getUsers'),
  },
  clients: {
    getAll: () => ipcRenderer.invoke('clients:getAll'),
    getById: (id) => ipcRenderer.invoke('clients:getById', id),
    create: (data) => ipcRenderer.invoke('clients:create', data),
    update: (id, data) => ipcRenderer.invoke('clients:update', id, data),
    delete: (id) => ipcRenderer.invoke('clients:delete', id),
    deleteAll: () => ipcRenderer.invoke('clients:deleteAll'),
    search: (q) => ipcRenderer.invoke('clients:search', q),
  },
  reservations: {
    getAll: () => ipcRenderer.invoke('reservations:getAll'),
    getById: (id) => ipcRenderer.invoke('reservations:getById', id),
    getByDate: (date) => ipcRenderer.invoke('reservations:getByDate', date),
    create: (data) => ipcRenderer.invoke('reservations:create', data),
    update: (id, data) => ipcRenderer.invoke('reservations:update', id, data),
    cancel: (id) => ipcRenderer.invoke('reservations:cancel', id),
    delete: (id) => ipcRenderer.invoke('reservations:delete', id),
    deleteAll: () => ipcRenderer.invoke('reservations:deleteAll'),
    checkConflict: (date, salle) => ipcRenderer.invoke('reservations:checkConflict', date, salle),
    getFinancialDetails: (id) => ipcRenderer.invoke('reservations:getFinancialDetails', id),
  },
  payments: {
    getAll: () => ipcRenderer.invoke('payments:getAll'),
    getByReservation: (id) => ipcRenderer.invoke('payments:getByReservation', id),
    search: (q) => ipcRenderer.invoke('payments:search', q),
    create: (data) => ipcRenderer.invoke('payments:create', data),
    update: (id, data) => ipcRenderer.invoke('payments:update', id, data),
    delete: (id) => ipcRenderer.invoke('payments:delete', id),
    deleteByReservation: (id) => ipcRenderer.invoke('payments:deleteByReservation', id),
    getReceiptData: (id) => ipcRenderer.invoke('payments:getReceiptData', id),
    getStats: () => ipcRenderer.invoke('payments:getStats'),
  },
  employees: {
    getAll: () => ipcRenderer.invoke('employees:getAll'),
    getById: (id) => ipcRenderer.invoke('employees:getById', id),
    create: (data) => ipcRenderer.invoke('employees:create', data),
    update: (id, data) => ipcRenderer.invoke('employees:update', id, data),
    delete: (id) => ipcRenderer.invoke('employees:delete', id),
    deleteAll: () => ipcRenderer.invoke('employees:deleteAll'),
    search: (q) => ipcRenderer.invoke('employees:search', q),
    getStats: () => ipcRenderer.invoke('employees:getStats'),
    getHistory: (id) => ipcRenderer.invoke('employees:getHistory', id),
    getByReservation: (id) => ipcRenderer.invoke('employees:getByReservation', id),
    assignToReservation: (data) => ipcRenderer.invoke('employees:assignToReservation', data),
    removeFromReservation: (empId, resId) => ipcRenderer.invoke('employees:removeFromReservation', empId, resId),
  },
  catering: {
    getTemplates: () => ipcRenderer.invoke('catering:getTemplates'),
    createTemplate: (data) => ipcRenderer.invoke('catering:createTemplate', data),
    updateTemplate: (id, data) => ipcRenderer.invoke('catering:updateTemplate', id, data),
    deleteTemplate: (id) => ipcRenderer.invoke('catering:deleteTemplate', id),
    getByReservation: (id) => ipcRenderer.invoke('catering:getByReservation', id),
    applyTemplate: (resId, templateId) => ipcRenderer.invoke('catering:applyTemplate', resId, templateId),
    save: (resId, data) => ipcRenderer.invoke('catering:save', resId, data),
    delete: (resId) => ipcRenderer.invoke('catering:delete', resId),
    getFicheData: (resId) => ipcRenderer.invoke('catering:getFicheData', resId),
    getStats: () => ipcRenderer.invoke('catering:getStats'),
  },
  expenses: {
    getGeneral: (month, year) => ipcRenderer.invoke('expenses:getGeneral', month, year),
    getByReservation: (id) => ipcRenderer.invoke('expenses:getByReservation', id),
    createGeneral: (data) => ipcRenderer.invoke('expenses:createGeneral', data),
    createForReservation: (data) => ipcRenderer.invoke('expenses:createForReservation', data),
    update: (id, data) => ipcRenderer.invoke('expenses:update', id, data),
    delete: (id) => ipcRenderer.invoke('expenses:delete', id),
    deleteAll: (month, year) => ipcRenderer.invoke('expenses:deleteAll', month, year),
  },
  finance: {
    getSummary: (month, year) => ipcRenderer.invoke('finance:getSummary', month, year),
    getAnnualSummary: (year) => ipcRenderer.invoke('finance:getAnnualSummary', year),
    getMonthlySummary: (year) => ipcRenderer.invoke('finance:getMonthlySummary', year),
    getStats: () => ipcRenderer.invoke('finance:getStats'),
  },
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    update: (data) => ipcRenderer.invoke('settings:update', data),
  },
  pdf: {
    generateReceipt: (data) => ipcRenderer.invoke('pdf:generateReceipt', data),
    generateCateringSheet: (data) => ipcRenderer.invoke('pdf:generateCateringSheet', data),
    print: (html) => ipcRenderer.invoke('pdf:print', html),
  },
  backup: {
    export: () => ipcRenderer.invoke('backup:export'),
    import: () => ipcRenderer.invoke('backup:import'),
  },
  packs: {
    getAll: () => ipcRenderer.invoke('packs:getAll'),
    getById: (id) => ipcRenderer.invoke('packs:getById', id),
    create: (data) => ipcRenderer.invoke('packs:create', data),
    update: (id, data) => ipcRenderer.invoke('packs:update', id, data),
    delete: (id) => ipcRenderer.invoke('packs:delete', id),
  },
});
